//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxOfShoes
    {
        public int BoxId { get; set; }
        public int ContainerId { get; set; }
        public int StockId { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
