//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Buyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buyer()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int BuyerId { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Discount { get; set; }

        public int NewDiscount
        {
            get
            {
                using (var context = new FootprintBaseEntities())
                {
                    int chequesCount = context.Cheque.Count(c => c.BuyerId == this.BuyerId);
                    return chequesCount >= 3 ? 30 : 0;
                }
            }
            set { }
        }

        public string PercentageDiscount
        {
            get
            {
                if (Discount.HasValue)
                {
                    if (NewDiscount != 0)
                    {
                        return $"{NewDiscount} %";
                    }
                    return "Без скидки";
                }
                else
                {
                    return "Без скидки";
                }
            }
            set { }
        }

        static string ConvertFullnameToShortname(string fullName)
        {
            var parts = fullName.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length < 3)
            {
                return fullName;
            }
            string shortSurname = parts[0];
            string shortName = parts[1][0] + ".";
            string shortPatronymic = parts[2][0] + ".";
            return $"{shortSurname} {shortName}{shortPatronymic}";
        }

        public string NewFIO
        {
            get
            {
                return ConvertFullnameToShortname(FIO);
            }
            set { }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
    }
}
