//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Cheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cheque()
        {
            this.ItemsInTheReceipt = new HashSet<ItemsInTheReceipt>();
        }
    
        public int ChequeId { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public int StaffId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public double TotalCostInChequeWithoutDiscount
        {
            get { return ItemsInTheReceipt.Sum(item => item.TotalCostWithoutDiscount); }
            set { }
        }

        public double TotalCostInCheque
        {
            get
            {
                return TotalCostInChequeWithoutDiscount * ((100 - NewDiscountInCheque) / 100.0);
            }
            set { }
        }

        public int NewDiscountInCheque
        {
            get
            {
                if (Buyer != null)
                {
                    return Buyer.NewDiscount;
                }
                else
                {
                    return 0;
                }
            }
            set { }
        }

        public string NewDateFormat
        {
            get
            {
                return DateOfSale.ToString("d");
            }
            set { }
        }
        public string NewTime
        {
            get
            {
                return DateOfSale.ToString("T");
            }
            set { }
        }

        public virtual Buyer Buyer { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInTheReceipt> ItemsInTheReceipt { get; set; }
    }
}
