//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.ReceivedGoods = new HashSet<ReceivedGoods>();
        }
    
        public int InvoiceId { get; set; }
        public int SuppliersId { get; set; }
        public System.DateTime DateOfReceipt { get; set; }

        public string NewDateFormat
        {
            get
            {
                return DateOfReceipt.ToString("d MMMM yyyy");
            }
            set { }
        }

        public string NewDateFormat1
        {
            get
            {
                return DateOfReceipt.ToString("g");
            }
            set { }
        }
        public string NewDateFormat2
        {
            get
            {
                return DateOfReceipt.ToString("d");
            }
            set { }
        }

        public int CountNumber
        {
            get { return ReceivedGoods.Count; }
            set { }
        }

        public double TotalCost
        {
            get { return ReceivedGoods.Sum(item => item.TotalCostInInvoice); }
            set { }
        }


        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivedGoods> ReceivedGoods { get; set; }
    }
}
