//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInTheReceipt
    {
        public int ItemsInTheReceiptId { get; set; }
        public int ChequeId { get; set; }
        public int ShoesId { get; set; }
        public int ShoeSize { get; set; }
        public int QuantityProduct { get; set; }

        public double TotalCostWithoutDiscount
        {
            get
            {
                return QuantityProduct * Shoes.Price;
            }
            set { }
        }

        private static int numberCounter = 1;
        private static int currentChequeId;
        public int Number
        {
            get
            {
                if (ChequeId != currentChequeId)
                {
                    currentChequeId = ChequeId;
                    numberCounter = 1;
                }
                return numberCounter++;
            }
            set { }
        }
        public virtual Cheque Cheque { get; set; }
        public virtual Shoes Shoes { get; set; }
        public virtual ShoeSize ShoeSize1 { get; set; }
    }
}
