//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootprintBaseEntities : DbContext
    {
        public FootprintBaseEntities()
            : base("name=FootprintBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLevels> AccessLevels { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Buyer> Buyer { get; set; }
        public virtual DbSet<Cheque> Cheque { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<ItemsInTheReceipt> ItemsInTheReceipt { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<Shoes> Shoes { get; set; }
        public virtual DbSet<ShoeSize> ShoeSize { get; set; }
        public virtual DbSet<ShoesType> ShoesType { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Container> Container { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<BoxOfShoes> BoxOfShoes { get; set; }
        public virtual DbSet<ReceivedGoods> ReceivedGoods { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
    }
}
