//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shoes()
        {
            this.ItemsInTheReceipt = new HashSet<ItemsInTheReceipt>();
            this.Container = new HashSet<Container>();
            this.ReceivedGoods = new HashSet<ReceivedGoods>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int ShoesId { get; set; }
        public string Name { get; set; }
        public int SeasonId { get; set; }
        public int ShoesTypeId { get; set; }
        public int BrandId { get; set; }
        public int ColorId { get; set; }
        public int MaterialId { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInTheReceipt> ItemsInTheReceipt { get; set; }
        public virtual Material Material { get; set; }
        public virtual Season Season { get; set; }
        public virtual ShoesType ShoesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> Container { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivedGoods> ReceivedGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
