//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Cheque = new HashSet<Cheque>();
            this.History = new HashSet<History>();
        }
    
        public int StaffId { get; set; }
        public string FIO { get; set; }
        public int PostId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string AccessLevel { get; set; }
        static string ConvertFullnameToShortname(string fullName)
        {
            var parts = fullName.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length < 3)
            {
                return fullName;
            }
            string shortSurname = parts[0];
            string shortName = parts[1][0] + ".";
            string shortPatronymic = parts[2][0] + ".";

            return $"{shortSurname} {shortName}{shortPatronymic}";
        }

        public string NewFIO
        {
            get
            {
                return ConvertFullnameToShortname(FIO);
            }
            set { }
        }
        public virtual AccessLevels AccessLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
    }
}
