//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footprint
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.BoxOfShoes = new HashSet<BoxOfShoes>();
        }
    
        public int StockId { get; set; }
        public int ShoesId { get; set; }
        public int ShoesSize { get; set; }
        public int QuantityProduct { get; set; }

        public int TotalQuantity
        {
            get
            {
                return MainWindow.baza.Stock.Where(rg => rg.ShoesId == ShoesId && rg.ShoesSize == ShoesSize).Sum(rg => rg.QuantityProduct);
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxOfShoes> BoxOfShoes { get; set; }
        public virtual Shoes Shoes { get; set; }
        public virtual ShoeSize ShoeSize { get; set; }
    }
}
